language: bash

os:
 - linux

install:
 - sudo apt-get --yes --force-yes update
 - sudo apt-get --yes --force-yes upgrade
 - sudo apt-get --yes --force-yes install make gcc fasm

before_script:
 - bash clean.sh

script:
 - bash make.sh

dist: xenial